spring:
    datasource:
        url: jdbc:mariadb://tardygramdb.cbstjjiyw4bi.ap-northeast-2.rds.amazonaws.com/tardygramdb
        driverClassName: org.mariadb.jdbc.Driver
        username: tardygramdb
        password: tardygramdb
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true
server:
    port: 9000
